[project]
name = "azul_ai_env"
version = "1.0.0"
description = "Library to enable AI agent training on Azul multiplayer game"
readme = "README.md"
requires-python = ">=3.12"

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"
